### ISSUE TITLE
Improved availability and stability of load-aware(usage plugin) scheduling function

### ISSUE THREAD

**Issue by wangyang0616** [volcano-sh/volcano#3175] opened 2023-11-05 07:49 UTC
**What happened**:
1. The load-aware scheduling monitoring system obtains the real CPU and Memory utilization of the node. Currently, Volcano directly queries data from prometheus through query. The architecture design is not elegant enough. You can refer to HPA/VPA to obtain monitoring indicators uniformly through custom metrics api.

2. The configuration information of the usage plug-in can be concisely optimized.

**What you expected to happen**:
1. While retaining existing capabilities, add a monitoring data source: custom metrics api
2. The configuration information of usage plugin is more concise and clear

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by william-wang** [comment] 2023-11-15 03:10
The issue is solved and close it.

**Closed by william-wang** 2023-11-15 03:10 UTC
Labels: kind/bug
