### ISSUE TITLE
can't create job due to the queue status is empty

### ISSUE THREAD

**Issue by Wang-Kai** [volcano-sh/volcano#3173] opened 2023-11-03 12:40 UTC
**What happened**:
I created a volcano queue, but the `status.state` is always empty, so i can't create any job as i want.

**What you expected to happen**:

The queue state is set to `Open` automatically, and i can create job use it freely.

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: test-video
  labels:
    tenant: video
spec:
  weight: 1
  reclaimable: false
```

kubectl get q test-video -o yaml 

```yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"scheduling.volcano.sh/v1beta1","kind":"Queue","metadata":{"annotations":{},"labels":{"tenant":"video","test":"true"},"name":"test-video"},"spec":{"reclaimable":false,"weight":1}}
  creationTimestamp: "2023-11-03T10:38:45Z"
  generation: 1
  labels:
    tenant: video
    test: "true"
  managedFields:
  - apiVersion: scheduling.volcano.sh/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:tenant: {}
          f:test: {}
      f:spec:
        .: {}
        f:reclaimable: {}
        f:weight: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2023-11-03T10:38:45Z"
  - apiVersion: scheduling.volcano.sh/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:guarantee: {}
      f:status:
        .: {}
        f:allocated:
          .: {}
          f:cpu: {}
          f:memory: {}
        f:reservation: {}
    manager: Go-http-client
    operation: Update
    time: "2023-11-03T10:38:48Z"
  name: test-video
  resourceVersion: "7166508002"
  uid: 5dfb01bc-66e0-4055-a51e-e58b5899b226
spec:
  reclaimable: false
  weight: 1
status:
  allocated:
    cpu: "0"
    memory: "0"
  reservation: {}
```

**Anything else we need to know?**:

While i create job, report 

```console
error: admission webhook "validatejob.volcano.sh" denied the request: can only submit job to queue with state `Open`, queue `test-video` status is ``;'
```

**Environment**:
- Volcano Version: v1.7.0
- Kubernetes version (use `kubectl version`): v1.20.15
- Cloud provider or hardware configuration:  x86-64
- OS : Debian GNU/Linux 9 (stretch)
- Kernel : Linux 5.10.0-103-bili-colo
- Install tools: helm

**Comment by Monokaix** [comment] 2023-11-04 07:25
Can you paste volcano-controller log about your queue to obtain more information?

**Comment by qutianhang1** [comment] 2023-11-14 13:15
Did you solve it? I encountered the same issue. I didn't have this problem when I installed Volcano before.

**Comment by qutianhang1** [comment] 2023-11-14 13:44
> 您可以粘贴有关您的队列的火山控制器日志以获取更多信息吗？

Error syncing queue request Queue: default, Job: /, Task:, Event:OutOfSync, ExitCode:0, Action:SyncQueue, JobVersion: 0 for sync queue default failed for Queue.scheduling.volcano.sh "default" is invalid: status.allocated: Invalid value: "null": status.allocated in body must be of type object: "null", event is OutOfSync, action is SyncQueue.

**Comment by william-wang** [comment] 2023-11-15 02:33
@Monokaix Have you reproduced in your env with v1.7?

**Comment by qutianhang1** [comment] 2023-11-15 05:56
> @Monokaix你用v1.7在你的环境中重现了吗？

yes，But I was able to install it normally before.  You can refer to my other issue.   https://github.com/volcano-sh/volcano/issues/3201

**Comment by Monokaix** [comment] 2023-11-15 08:30
I run volcano with kubernetes version 1.23, both latest and v1.7.0 of volcano can not reproduce it, can you try another time with kubernetes version 1.23?

**Comment by Monokaix** [comment] 2023-11-15 08:57
Also what's the schedule-period you set?

**Comment by Monokaix** [comment] 2023-11-15 09:58
Hi, here is the root cause, and will be fixed soon. https://github.com/volcano-sh/volcano/issues/3201#issuecomment-1812131194

**Closed** 2023-11-17 07:46 UTC
Labels: kind/bug
