### ISSUE TITLE
generate-yaml volcano-monitoring-latest.yaml diffrent

### ISSUE THREAD

**Issue by lengrongfu** [volcano-sh/volcano#3779] opened 2024-10-17 03:21 UTC
### Description

When i change chart file, then exec `make generate-yaml TAG=latest RELEASE_DIR=installer` command, every time volcano-monitoring-latest.yaml this file will change, remove the following code.

https://github.com/volcano-sh/volcano/blob/8d05ea0ea56a23c03a083ea350fd30d2c88249ac/installer/volcano-monitoring-latest.yaml#L449-L450

because `$kube_state_metrics_ns` this var is not value.
https://github.com/volcano-sh/volcano/blob/8d05ea0ea56a23c03a083ea350fd30d2c88249ac/installer/helm/chart/volcano/templates/kubestatemetrics.yaml#L188-L190

https://github.com/volcano-sh/volcano/blob/8d05ea0ea56a23c03a083ea350fd30d2c88249ac/installer/helm/chart/volcano/templates/kubestatemetrics.yaml#L2

I found in values.yaml file not define value for this two var `.Values.custom.kube_state_metrics_ns`  and `.Values.custom.default_ns`.

I can't trace the history.  

Can someone tell me how I should modify it? is change volcano-monitoring-latest.yaml this file or and node select to values.yaml?

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

Hope exec `make generate-yaml TAG=latest RELEASE_DIR=installer` this command, no other changes will occur.

### What version of Volcano are you using?

master

**Comment by fengruotj** [comment] 2024-10-17 16:43
@volcano-sh-bot I am very interested in this issue, please assign it to me. Maybe, we can remove the nodeSelector default value from the volcano/installer/volcano-monitoring-latest.yaml file.

**Comment by Monokaix** [comment] 2024-10-18 01:54
caused by https://github.com/volcano-sh/volcano/pull/3740

**Comment by fengruotj** [comment] 2024-10-18 03:03
@lengrongfu @Monokaix  Hi all, maybe we can remove the default nodeSelector value from the volcano monitoring installation yaml.

**Closed** 2024-10-18 14:44 UTC
Labels: help wanted, good first issue, kind/bug
