### ISSUE TITLE
Qeueue.Status is always empty, resulting in job not being created.

### ISSUE THREAD

**Issue by qutianhang1** [volcano-sh/volcano#3201] opened 2023-11-14 14:18 UTC
**What happened**:
I created a volcano queue, but the status is always empty, so i can't create any job as i want.

**What you expected to happen**:
The queue state is set to Open automatically, and i can create job use it freely.

**How to reproduce it (as minimally and precisely as possible)**:

kubectl apply -f volcano-queue.yaml

```yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: volcano-test
spec:
  weight: 1
  reclaimable: false
  capability:
    cpu: "6121"
    memory: "50083Gi"
    momenta.ai/rdma: "999"
    nvidia.com/gpu: "999"
```

kubectl get queue volcano-test -o yaml

```yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"scheduling.volcano.sh/v1beta1","kind":"Queue","metadata":{"annotations":{},"name":"volcano-test"},"spec":{"capability":{"cpu":"6121","memory":"50083Gi","momenta.ai/rdma":"999","nvidia.com/gpu":"999"},"reclaimable":false,"weight":1}}
  creationTimestamp: "2023-11-14T14:11:50Z"
  generation: 1
  name: volcano-test
  resourceVersion: "2219060399"
  selfLink: /apis/scheduling.volcano.sh/v1beta1/queues/volcano-test
  uid: 3695f53c-f7f5-4482-a061-1e67d067e067
spec:
  capability:
    cpu: "6121"
    memory: 50083Gi
    momenta.ai/rdma: "999"
    nvidia.com/gpu: "999"
  reclaimable: false
  weight: 1

```

**Anything else we need to know?**:

controller log:
```yaml
I1114 14:14:34.358025       1 queue_controller_action.go:35] Begin to sync queue volcano-test.
E1114 14:14:34.390222       1 queue_controller_action.go:79] Failed to update status of Queue volcano-test: Queue.scheduling.volcano.sh "volcano-test" is invalid: status.allocated: Invalid value: "null": status.allocated in body must be of type object: "null".
I1114 14:14:34.390237       1 queue_controller_action.go:80] End sync queue volcano-test.
```
error：

```yaml
HTTP response headers: HTTPHeaderDict({'Audit-Id': '4305b9ef-95c4-4a67-b453-cd3795cec4dd', 'Content-Type': 'application/json', 'Date': 'Tue, 14 Nov 2023 12:58:28 GMT', 'Content-Length': '240'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"admission webhook \"validatejob.volcano.sh\" denied the request: can only submit job to queue with state `Open`, queue `volcano-test` status is ``;","code":400}

```

**Environment**:
Volcano Version: latest
Kubernetes version (use kubectl version): v1.17
Cloud provider or hardware configuration: x86-64
OS : Debian GNU/Linux 9 (stretch)
Kernel : Linux 5.10.0-103-bili-colo
Install tools:  kubectl create -f  https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml

**Comment by Monokaix** [comment] 2023-11-15 08:11
Do you upgrade your volcano version or just installed the latest version in a clean cluster without volcano installed before?

**Comment by qutianhang1** [comment] 2023-11-15 09:39
> Do you upgrade your volcano version or just installed the latest version in a clean cluster without volcano installed before?

 Previously, Volcano was installed on the cluster, this time the latest version is being installed.  Does the latest version no longer support 1.17? how can I install the previous version of Volcano? Or do I need to upgrade the cluster version to install the latest Volcano?

**Comment by Monokaix** [comment] 2023-11-15 09:53
> > Do you upgrade your volcano version or just installed the latest version in a clean cluster without volcano installed before?
> 
> Previously, Volcano was installed on the cluster, this time the latest version is being installed. Does the latest version no longer support 1.17? how can I install the previous version of Volcano? Or do I need to upgrade the cluster version to install the latest Volcano?

Hi, after code digging, the root cause has been found, and it's nothing to do with kubernetes version.
When creating a queue, the default status.allocated is nil, and then if the allocated is not assigned when updating the queue, the update will fail, and the retry will only be 15 times, then the queue will not be processed again, that is to say, the updated allocated of the queue will be completed within 15 retries. Now, the update of the status.allocated field of the queue is performed on each closesession of volcano-scheduler, which means that if a session takes a long time and then the queue is created at this time, the update will fail.

**Comment by Monokaix** [comment] 2023-11-15 09:56
Also you can check version compatibility [here](https://github.com/volcano-sh/volcano#kubernetes-compatibility).

**Comment by qutianhang1** [comment] 2023-11-15 10:09
> Also you can check version compatibility [here](https://github.com/volcano-sh/volcano#kubernetes-compatibility).

 It seems the latest version indeed does not support 1.17 anymore, but the previous installation appeared to be normal.

**Comment by qutianhang1** [comment] 2023-11-15 10:13
> > status
> 
> > > > Do you upgrade your volcano version or just installed the latest version in a clean cluster without volcano installed before?
> > > 
> > > 
> > > Previously, Volcano was installed on the cluster, this time the latest version is being installed. Does the latest version no longer support 1.17? how can I install the previous version of Volcano? Or do I need to upgrade the cluster version to install the latest Volcano?
> > 
> > 
> > Hi, after code digging, the root cause has been found, and it's nothing to do with kubernetes version. When creating a queue, the default status.allocated is nil, and then if the allocated is not assigned when updating the queue, the update will fail, and the retry will only be 15 times, then the queue will not be processed again, that is to say, the updated allocated of the queue will be completed within 15 retries. Now, the update of the status.allocated field of the queue is performed on each closesession of volcano-scheduler, which means that if a session takes a long time and then the queue is created at this time, the update will fail.
> 
> : So how can this be resolved?Could it be the issue with the cluster? Should I try with a different cluster?

**Comment by Monokaix** [comment] 2023-11-17 09:05
/close
Fixed by https://github.com/volcano-sh/volcano/pull/3206

**Closed by Monokaix** 2023-11-17 09:05 UTC
Labels: kind/bug
